import { test, expect } from "@playwright/test";
import { emptySurvey } from "../src/survey/model";
const adminHeaders = { Authorization: "Bearer local-test-only-survey-key-123456" };

test("D1 validates input, denies anonymous reads, and deduplicates retries", async ({ request }) => {
  const answer = emptySurvey(); answer.parent.feedback = "ローカル自動テスト";
  expect((await request.get("/api/survey/admin")).status()).toBe(401);
  expect((await request.get("/api/survey/admin", { headers: { Authorization: "Bearer wrong" } })).status()).toBe(401);
  expect((await request.post("/api/survey", { data: answer, headers: { Origin: "https://foreign.example" } })).status()).toBe(403);
  expect((await request.post("/api/survey", { data: { ...answer, consent: false }, headers: { Origin: "http://127.0.0.1:4187" } })).status()).toBe(400);
  for (let i = 0; i < 2; i++) expect((await request.post("/api/survey", { data: answer, headers: { Origin: "http://127.0.0.1:4187" } })).status()).toBe(200);
  const response = await request.get("/api/survey/admin", { headers: adminHeaders });
  expect(response.headers()["cache-control"]).toBe("no-store");
  expect((await response.json()).rows.filter((r: any) => r.response.id === answer.id)).toHaveLength(1);
});

test("mobile child and parent survey retries and administrator can export", async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/?survey=1");
  await expect(page.getByRole("button", { name: "アンケートを はじめる" })).toBeDisabled();
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "アンケートを はじめる" }).click();
  await page.getByRole("button", { name: "たのしかった", exact: true }).click();
  await page.screenshot({ path: info.outputPath("child-survey.png") });
  await page.getByRole("button", { name: "つぎへ →" }).click();
  await page.getByRole("button", { name: "こたえないで つぎへ" }).click();
  await page.getByLabel("年齢（歳）").fill("5");
  await page.getByRole("checkbox", { name: "外遊び・運動", exact: true }).check();
  await page.getByRole("checkbox", { name: "お絵描き・工作", exact: true }).check();
  await page.getByRole("radio", { name: "30分未満", exact: true }).check();
  await page.getByRole("radio", { name: "タブレット", exact: true }).check();
  await page.getByRole("radio", { name: "合っている", exact: true }).check();
  await page.getByRole("checkbox", { name: /謝辞に、入力した名前を掲載してよい/ }).check();
  await page.getByLabel("謝辞に載せるお名前（ニックネーム・本名どちらも可）").fill("ローカル謝辞テスト");
  await page.getByRole("checkbox", { name: /大会の結果と感謝のメールを受け取りたい/ }).check();
  await page.getByLabel("保護者のメールアドレス", { exact: true }).fill("local-parent@example.test");
  await page.getByLabel("お礼メールで使うお子さまの呼び名（任意）").fill("テスト呼び名");
  const cooperation = page.getByRole("checkbox", { name: "体験している様子の提供に協力できるので、開発者から連絡を受け取ってよい" });
  const cooperationEmail = page.getByLabel("体験の様子の提供についての連絡用メールアドレス（保護者）");
  await expect(cooperationEmail).toHaveCount(0);
  await cooperation.check();
  await cooperationEmail.fill("cleared@example.test");
  await cooperation.uncheck();
  await cooperation.check();
  await expect(cooperationEmail).toHaveValue("");
  await cooperationEmail.fill("experience@example.test");
  await page.getByRole("heading", { name: "最後に、ご希望の方だけ" }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath("optional-contact.png") });
  await page.getByRole("button", { name: "送信前に確認する" }).click();
  await expect(page.getByText("local-parent@example.test", { exact: true })).toBeVisible();
  await page.route("**/api/survey", route => route.abort(), { times: 1 });
  await page.getByRole("button", { name: "同意して送信する" }).click();
  await expect(page.getByRole("alert")).toContainText("送信できません");
  expect(await page.evaluate(() => sessionStorage.getItem("otocanvas.survey.pending.v1"))).not.toContain("local-parent@example.test");
  expect(await page.evaluate(() => sessionStorage.getItem("otocanvas.survey.pending.v1"))).not.toContain("experience@example.test");
  await page.getByRole("button", { name: "同意して送信する" }).click();
  await expect(page.getByRole("heading", { name: "ありがとう！" })).toBeVisible();
  await page.goto("/?survey=admin");
  await page.getByLabel("管理キー", { exact: true }).fill("local-test-only-survey-key-123456");
  await page.getByRole("button", { name: "集計を表示・更新" }).click();
  await expect(page.getByRole("heading", { name: "子ども：また遊びたい？" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "普段、お子さまはどんな遊びをしていますか？（複数選択可）", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "普段、1日あたり端末をどれくらい使いますか？", exact: true })).toBeVisible();
  await page.getByText("謝辞・お礼・体験提供の連絡先（分析には使用しない）", { exact: true }).click();
  await expect(page.locator("details.survey-contact").getByText("local-parent@example.test", { exact: true }).first()).toBeVisible();
  await expect(page.locator("details.survey-contact").getByText("experience@example.test", { exact: true }).first()).toBeVisible();
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: "絞り込んだ回答をCSV保存" }).click();
  expect((await download).suggestedFilename()).toBe("otocanvas-survey.csv");
  expect(await page.locator(".survey-shell").evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath("admin-survey.png") });
  await page.getByRole("button", { name: "ログアウト", exact: true }).click();
  await expect(page.locator(".survey-chart")).toHaveCount(0);
});
// 本番には触れず、ローカルD1で削除権限・再送・復元まで検証する。
test("administrator can cancel, trash and restore a response without affecting others", async ({ page, request }) => {
  const answer = emptySurvey(); answer.parent.feedback = "削除復元テスト";
  const other = emptySurvey();
  const origin = { Origin: "http://127.0.0.1:4187" };
  for (const data of [answer, other]) expect((await request.post("/api/survey", { data, headers: origin })).status()).toBe(200);
  const action = { id: answer.id, action: "trash" };
  expect((await request.post("/api/survey/admin", { data: action, headers: origin })).status()).toBe(401);
  expect((await request.get("/api/survey/admin?trash=1")).status()).toBe(401);
  expect((await request.post("/api/survey/admin", { data: action, headers: { ...adminHeaders, Origin: "https://foreign.example" } })).status()).toBe(403);
  expect((await request.post("/api/survey/admin", { data: { id: "bad", action: "trash" }, headers: { ...adminHeaders, ...origin } })).status()).toBe(400);
  await page.goto("/?survey=admin");
  await page.getByLabel("管理キー", { exact: true }).fill("local-test-only-survey-key-123456");
  await page.getByRole("button", { name: "集計を表示・更新" }).click();
  await page.getByText("回答の管理・デバッグ回答の削除", { exact: true }).click();
  await page.getByLabel("回答ID・内容・日時で検索").fill(answer.id);
  const row = page.locator(`[data-response-id="${answer.id}"]`);
  await row.locator("summary").click();
  page.once("dialog", dialog => dialog.dismiss());
  await page.getByRole("button", { name: "この回答をゴミ箱へ移す", exact: true }).click();
  await expect(row).toBeVisible();
  page.once("dialog", dialog => dialog.accept());
  await page.getByRole("button", { name: "この回答をゴミ箱へ移す", exact: true }).click();
  await expect(row).toHaveCount(0);
  let active = await (await request.get("/api/survey/admin", { headers: adminHeaders })).json();
  expect(active.rows.some((r: any) => r.response.id === answer.id)).toBe(false);
  expect(active.rows.some((r: any) => r.response.id === other.id)).toBe(true);
  expect((await request.post("/api/survey", { data: answer, headers: origin })).status()).toBe(200);
  active = await (await request.get("/api/survey/admin", { headers: adminHeaders })).json();
  expect(active.rows.some((r: any) => r.response.id === answer.id)).toBe(false);
  await page.getByRole("button", { name: "ゴミ箱を表示・更新", exact: true }).click();
  await row.locator("summary").click();
  await page.getByRole("button", { name: "この回答を復元する", exact: true }).click();
  await expect(row).toHaveCount(0);
  await page.getByRole("button", { name: "集計中の回答", exact: true }).click();
  await expect(row).toBeVisible();
  active = await (await request.get("/api/survey/admin", { headers: adminHeaders })).json();
  expect(active.rows.filter((r: any) => r.response.id === answer.id)).toHaveLength(1);
  expect(active.rows.find((r: any) => r.response.id === answer.id).response.parent.feedback).toBe("削除復元テスト");
});
