import {
  BARS,
  type CanvasShape,
  type MusicEvent,
  type OtoProject,
} from "../types/project";

export const PROJECT_DATABASE_NAME = "oto-canvas";
export const PROJECT_STORE_NAME = "projects";
export const PROJECT_STORAGE_VERSION = 1;

const DATABASE_VERSION = 1;
const FALLBACK_STORAGE_KEY = "oto-canvas:projects:v1";

interface FallbackEnvelope {
  version: 1;
  projects: OtoProject[];
}

const memoryFallback = new Map<string, OtoProject>();
let databasePromise: Promise<IDBDatabase> | null = null;

const SHAPE_KINDS = new Set([
  "circle",
  "triangle",
  "line",
  "square",
  "diamond",
  "star",
  "hexagon",
  "ring",
  "pen",
]);
const WORLD_IDS = new Set(["soft", "bounce", "space"]);
const SECTIONS = new Set(["intro", "a", "b", "break", "climax", "outro"]);
const VISUAL_EVENTS = new Set(["pulse", "orbit", "wave", "split", "fade"]);
// Keep the original four ids readable so projects saved before the
// shape-specific instrument update still restore without a migration.
const INSTRUMENTS = new Set([
  "marimba",
  "drum",
  "piano",
  "harp",
  "glockenspiel",
  "kalimba",
  "chime",
  "flute",
  "bell",
  "percussion",
  "bass",
  "pad",
]);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function isPoint(value: unknown): boolean {
  return (
    isRecord(value) &&
    isFiniteNumber(value.x) &&
    isFiniteNumber(value.y)
  );
}

function isCanvasShape(value: unknown): value is CanvasShape {
  if (!isRecord(value) || !isRecord(value.position)) return false;

  return (
    typeof value.id === "string" &&
    value.id.length > 0 &&
    typeof value.kind === "string" &&
    SHAPE_KINDS.has(value.kind) &&
    isFiniteNumber(value.position.x) &&
    isFiniteNumber(value.position.y) &&
    isFiniteNumber(value.size) &&
    isFiniteNumber(value.rotation) &&
    typeof value.colorId === "string" &&
    typeof value.patternId === "string" &&
    isFiniteNumber(value.zIndex) &&
    (value.scene === undefined || value.scene === 0 || value.scene === 1 || value.scene === 2) &&
    (value.points === undefined ||
      (Array.isArray(value.points) && value.points.every(isPoint)))
  );
}

function isMusicEvent(value: unknown): value is MusicEvent {
  if (!isRecord(value)) return false;

  return (
    typeof value.id === "string" &&
    value.id.length > 0 &&
    typeof value.shapeId === "string" &&
    isFiniteNumber(value.beat) &&
    isFiniteNumber(value.durationBeats) &&
    (value.midiNote === undefined || isFiniteNumber(value.midiNote)) &&
    isFiniteNumber(value.velocity) &&
    typeof value.instrumentId === "string" &&
    INSTRUMENTS.has(value.instrumentId) &&
    typeof value.section === "string" &&
    SECTIONS.has(value.section) &&
    typeof value.visualEvent === "string" &&
    VISUAL_EVENTS.has(value.visualEvent)
  );
}

/** Checks metadata shared by current and supported legacy v1 projects. */
function hasProjectMetadata(value: unknown): value is Record<string, unknown> {
  if (!isRecord(value)) return false;

  return (
    value.version === PROJECT_STORAGE_VERSION &&
    typeof value.id === "string" &&
    value.id.length > 0 &&
    (value.title === undefined || typeof value.title === "string") &&
    isFiniteNumber(value.createdAt) &&
    isFiniteNumber(value.updatedAt) &&
    isFiniteNumber(value.seed) &&
    typeof value.worldId === "string" &&
    WORLD_IDS.has(value.worldId) &&
    value.bpm === 96 &&
    Array.isArray(value.shapes) &&
    value.shapes.every(isCanvasShape)
  );
}

/** Validates the current format used for every new save. */
export function isOtoProject(value: unknown): value is OtoProject {
  return (
    hasProjectMetadata(value) &&
    value.bars === BARS &&
    Array.isArray(value.events) &&
    value.events.every(isMusicEvent)
  );
}

/**
 * OtoCanvas v1 originally used 84 bars. Keep recognizing that exact legacy
 * duration so existing local projects survive the switch to a 30-second MV.
 * Events are regenerated by the app, so stale 84-bar events are discarded.
 */
function migrateProject(value: unknown): OtoProject | null {
  if (isOtoProject(value)) return cloneProject(value);
  if (
    !hasProjectMetadata(value) ||
    value.bars !== 84 ||
    !Array.isArray(value.events)
  ) {
    return null;
  }

  return cloneProject({
    version: PROJECT_STORAGE_VERSION,
    id: value.id as string,
    ...(typeof value.title === "string" ? { title: value.title } : {}),
    createdAt: value.createdAt as number,
    updatedAt: value.updatedAt as number,
    seed: value.seed as number,
    worldId: value.worldId as OtoProject["worldId"],
    bpm: 96,
    bars: BARS,
    shapes: value.shapes as CanvasShape[],
    events: [],
  });
}

function cloneProject(project: OtoProject): OtoProject {
  if (typeof structuredClone === "function") {
    return structuredClone(project);
  }

  return JSON.parse(JSON.stringify(project)) as OtoProject;
}

function openDatabase(): Promise<IDBDatabase> {
  if (typeof indexedDB === "undefined") {
    return Promise.reject(new Error("IndexedDB is not available."));
  }

  if (databasePromise) return databasePromise;

  const attempt = new Promise<IDBDatabase>((resolve, reject) => {
    const request = indexedDB.open(PROJECT_DATABASE_NAME, DATABASE_VERSION);

    request.onupgradeneeded = () => {
      const database = request.result;
      if (!database.objectStoreNames.contains(PROJECT_STORE_NAME)) {
        const store = database.createObjectStore(PROJECT_STORE_NAME, {
          keyPath: "id",
        });
        store.createIndex("updatedAt", "updatedAt", { unique: false });
      }
    };

    request.onsuccess = () => {
      const database = request.result;
      database.onversionchange = () => database.close();
      resolve(database);
    };
    request.onerror = () => reject(request.error ?? new Error("Could not open IndexedDB."));
    request.onblocked = () => reject(new Error("IndexedDB upgrade is blocked by another tab."));
  });

  databasePromise = attempt;
  void attempt.catch(() => {
    if (databasePromise === attempt) databasePromise = null;
  });
  return attempt;
}

function requestResult<T>(request: IDBRequest<T>): Promise<T> {
  return new Promise((resolve, reject) => {
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error ?? new Error("IndexedDB request failed."));
  });
}

function transactionComplete(transaction: IDBTransaction): Promise<void> {
  return new Promise((resolve, reject) => {
    transaction.oncomplete = () => resolve();
    transaction.onabort = () =>
      reject(transaction.error ?? new Error("IndexedDB transaction was aborted."));
    transaction.onerror = () => {
      // The abort handler provides the final transaction error.
    };
  });
}

async function idbPut(project: OtoProject): Promise<void> {
  const database = await openDatabase();
  const transaction = database.transaction(PROJECT_STORE_NAME, "readwrite");
  const completion = transactionComplete(transaction);
  const request = requestResult(transaction.objectStore(PROJECT_STORE_NAME).put(project));
  await Promise.all([request, completion]);
}

async function idbGet(id: string): Promise<unknown> {
  const database = await openDatabase();
  const transaction = database.transaction(PROJECT_STORE_NAME, "readonly");
  const completion = transactionComplete(transaction);
  const request = requestResult(transaction.objectStore(PROJECT_STORE_NAME).get(id));
  const [result] = await Promise.all([request, completion]);
  return result;
}

async function idbGetAll(): Promise<unknown[]> {
  const database = await openDatabase();
  const transaction = database.transaction(PROJECT_STORE_NAME, "readonly");
  const completion = transactionComplete(transaction);
  const request = requestResult(transaction.objectStore(PROJECT_STORE_NAME).getAll());
  const [result] = await Promise.all([request, completion]);
  return result;
}

async function idbDelete(id: string): Promise<void> {
  const database = await openDatabase();
  const transaction = database.transaction(PROJECT_STORE_NAME, "readwrite");
  const completion = transactionComplete(transaction);
  const request = requestResult(transaction.objectStore(PROJECT_STORE_NAME).delete(id));
  await Promise.all([request, completion]);
}

async function idbClear(): Promise<void> {
  const database = await openDatabase();
  const transaction = database.transaction(PROJECT_STORE_NAME, "readwrite");
  const completion = transactionComplete(transaction);
  const request = requestResult(transaction.objectStore(PROJECT_STORE_NAME).clear());
  await Promise.all([request, completion]);
}

function browserStorage(): Storage | null {
  try {
    return typeof localStorage === "undefined" ? null : localStorage;
  } catch {
    return null;
  }
}

function mergeProjects(...collections: readonly OtoProject[][]): OtoProject[] {
  const projects = new Map<string, OtoProject>();

  for (const collection of collections) {
    for (const project of collection) {
      const previous = projects.get(project.id);
      if (!previous || project.updatedAt >= previous.updatedAt) {
        projects.set(project.id, cloneProject(project));
      }
    }
  }

  return [...projects.values()].sort((a, b) => b.updatedAt - a.updatedAt);
}

function readFallbackProjects(): OtoProject[] {
  const inMemory = [...memoryFallback.values()];
  const storage = browserStorage();
  if (!storage) return mergeProjects(inMemory);

  try {
    const raw = storage.getItem(FALLBACK_STORAGE_KEY);
    if (!raw) return mergeProjects(inMemory);

    const parsed: unknown = JSON.parse(raw);
    if (!isRecord(parsed) || parsed.version !== 1 || !Array.isArray(parsed.projects)) {
      return mergeProjects(inMemory);
    }

    const valid = parsed.projects
      .map(migrateProject)
      .filter((project): project is OtoProject => project !== null);
    return mergeProjects(valid, inMemory);
  } catch {
    return mergeProjects(inMemory);
  }
}

function writeFallbackProjects(projects: readonly OtoProject[]): void {
  memoryFallback.clear();
  for (const project of projects) {
    memoryFallback.set(project.id, cloneProject(project));
  }

  const envelope: FallbackEnvelope = {
    version: 1,
    projects: [...memoryFallback.values()],
  };

  try {
    browserStorage()?.setItem(FALLBACK_STORAGE_KEY, JSON.stringify(envelope));
  } catch {
    // Private browsing or a full quota can reject localStorage. The in-memory
    // copy still keeps the current session usable.
  }
}

function saveToFallback(project: OtoProject): void {
  const projects = readFallbackProjects().filter((item) => item.id !== project.id);
  projects.push(cloneProject(project));
  writeFallbackProjects(projects);
}

function deleteFromFallback(id: string): void {
  writeFallbackProjects(readFallbackProjects().filter((project) => project.id !== id));
}

function clearFallback(): void {
  memoryFallback.clear();
  try {
    browserStorage()?.removeItem(FALLBACK_STORAGE_KEY);
  } catch {
    // The in-memory store has still been cleared.
  }
}

/** Saves a defensive copy and returns the exact stored value. */
export async function saveProject(project: OtoProject): Promise<OtoProject> {
  if (!isOtoProject(project)) {
    throw new TypeError("Cannot save an invalid or unsupported OtoCanvas project.");
  }

  const stored = cloneProject({
    ...project,
    updatedAt: Date.now(),
  });

  try {
    await idbPut(stored);
    deleteFromFallback(stored.id);
  } catch {
    saveToFallback(stored);
  }

  return cloneProject(stored);
}

/** Loads a project by id, returning null for missing, corrupt, or future data. */
export async function loadProject(id: string): Promise<OtoProject | null> {
  let indexedProject: OtoProject | null = null;

  try {
    const value = await idbGet(id);
    indexedProject = migrateProject(value);
  } catch {
    // Fall through to the localStorage/in-memory copy.
  }

  const fallbackProject = readFallbackProjects().find((project) => project.id === id) ?? null;
  if (!indexedProject) return fallbackProject ? cloneProject(fallbackProject) : null;
  if (!fallbackProject) return indexedProject;
  return cloneProject(
    fallbackProject.updatedAt > indexedProject.updatedAt ? fallbackProject : indexedProject,
  );
}

/** Lists valid projects, newest first. */
export async function listProjects(): Promise<OtoProject[]> {
  let indexedProjects: OtoProject[] = [];

  try {
    indexedProjects = (await idbGetAll())
      .map(migrateProject)
      .filter((project): project is OtoProject => project !== null);
  } catch {
    // A blocked/disabled IndexedDB still leaves the fallback available.
  }

  return mergeProjects(indexedProjects, readFallbackProjects());
}

export async function loadLatestProject(): Promise<OtoProject | null> {
  const [latest] = await listProjects();
  return latest ? cloneProject(latest) : null;
}

export async function deleteProject(id: string): Promise<void> {
  try {
    await idbDelete(id);
  } catch {
    // Deleting the fallback still hides a fallback-only project.
  }
  deleteFromFallback(id);
}

export async function clearProjects(): Promise<void> {
  try {
    await idbClear();
  } catch {
    // IndexedDB may be unavailable; always clear the active fallback too.
  }
  clearFallback();
}

export const projectStore = {
  save: saveProject,
  load: loadProject,
  loadLatest: loadLatestProject,
  list: listProjects,
  delete: deleteProject,
  clear: clearProjects,
};
